Portfolio desktop version
saqibjavaiddev/My-Portfolio pull request #4
Opened 2022-06-01 17:44 UTC by saqibjavaiddev

During this project I made my portfolio responsive for desktop and mobile version. For this I used media queries. During this project I learned:

- How to create UIs adaptable to different screen sizes using media queries.
- How to parse a Figma design to create a UI.

2022-06-01 18:21 UTC, Mre55 requested changes
**Hi @saqibjavaiddev,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 18:21 UTC, Mre55 commented on assets/style.css
> +}
Kindly match your `work` section with the design provided in your desktop view there is unnecessary white space on the right please edit that.


| Your Design |
|-------------|
| <img width="1347" alt="image" src="https://user-images.githubusercontent.com/34578631/171473593-a344c47b-660a-433d-af73-47d2b2fd33e2.png"> | 
| Figma Design |
| <img width="1167" alt="image" src="https://user-images.githubusercontent.com/34578631/171473653-aa5bf82b-1bf5-4a84-9c6e-27c6e9b134e2.png">|

2022-06-01 18:30 UTC, saqibjavaiddev commented on assets/style.css
> +}
Center aligned everything and increased the font weight

2022-06-01 19:15 UTC, saqibjavaiddev commented on assets/style.css
> +}
Removed unnecessary white space on the right

2022-06-01 19:16 UTC, saqibjavaiddev commented on assets/style.css
> +}
Replaced **h1** for about me with **h2**.

2022-06-01 19:50 UTC, saqibjavaiddev commented on assets/style.css
> +}
Centered the whole content of thesection and edited **li** background for the Language.

2022-06-01 21:15 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @saqibjavaiddev 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Rewquired changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 21:15 UTC, tresorsawasawa commented on assets/style.css
> +  }
- [ **OPTIONAL** ]  Great job by making all changes required by the previous reviewer. But, I suggest also using the correct color provided by Figma on texts in the `about_me` section such as: `About
Myself`, `Frameworks`, etc to make your design match Figma design.

- [ **OPTIONAL** ] For best practices and not repeat yourself every time, I suggest you wrap all the `desktop version` styling in only one `@media query`. This will make your code to be clean
 ```bash
  @media only screen and (max-width: 768px) {
    all code about desktop styling
  }
````

2022-06-02 05:02 UTC, saqibjavaiddev commented on assets/style.css
> +}
Both image and text section given width half half, added spacing and margin. Also fixed the even childs

2022-06-02 05:02 UTC, saqibjavaiddev commented on assets/style.css
> +}
Height for desktop version also fixed

2022-06-02 05:58 UTC, saqibjavaiddev commented on index.html
>                  like what you see and have a project you need coded, don’t hestiate to
Changed font-size for desktop version

2022-06-02 05:59 UTC, saqibjavaiddev commented on assets/style.css
> +}
Margin added similar to figma design

2022-06-02 06:18 UTC, saqibjavaiddev commented on assets/style.css
> +  }
- Changed color for desktop version
- Wrapped all media queries for desktop and mobile

2022-06-02 07:43 UTC, Mre55 requested changes
**Hi @saqibjavaiddev,**

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions 🟡 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 07:43 UTC, Mre55 commented on assets/style.css
> +  }
Good job 👍 implementing the changes requested by the preview reviewer, there is one missing point in your images for the project section currently displayed out of the box container kindly fix that.

https://user-images.githubusercontent.com/34578631/171579726-51b35afa-5a11-41ab-946a-dcf5ff2b08e6.mov

2022-06-02 08:03 UTC, saqibjavaiddev commented on assets/style.css
> +  }
On my side its not showing like this, but I still fixed it. by given it specific height instead of auto Thanks for the review

2022-06-02 08:08 UTC, mikethreels approved these changes
Hi Saqib, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 08:10 UTC, merged